//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivoShop.customControls.Navigation.Desktop {
    
    
    public partial class HorizontalMenuSecondLevel {
        
        /// <summary>
        /// SecondLevelColumn1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VivoShop.customControls.Navigation.Desktop.HorizotnalMenuSecondLevelItem SecondLevelColumn1;
        
        /// <summary>
        /// SecondLevelColumn2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VivoShop.customControls.Navigation.Desktop.HorizotnalMenuSecondLevelItem SecondLevelColumn2;
        
        /// <summary>
        /// SecondLevelColumn3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VivoShop.customControls.Navigation.Desktop.HorizotnalMenuSecondLevelItem SecondLevelColumn3;
        
        /// <summary>
        /// SecondLevelColumn4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VivoShop.customControls.Navigation.Desktop.HorizotnalMenuSecondLevelItem SecondLevelColumn4;
    }
}
