//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivoShop.customControls.BlockProductsColumns {
    
    
    public partial class BlockProductsColumns {
        
        /// <summary>
        /// column1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VivoShop.customControls.BlockProductsColumns.BlockProductsColumnsColumn column1;
        
        /// <summary>
        /// column2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VivoShop.customControls.BlockProductsColumns.BlockProductsColumnsColumn column2;
        
        /// <summary>
        /// column3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VivoShop.customControls.BlockProductsColumns.BlockProductsColumnsColumn column3;
    }
}
